// Generated by CoffeeScript 1.3.1
(function() {
  var body, button, cmd, load, obeyMouseEvents, releaseEvents, rocker, tag, touchEvents,
    __hasProp = {}.hasOwnProperty;

  tag = function(opts) {
    var k, t, v, _ref;
    t = document.createElement((_ref = opts.name) != null ? _ref : 'div');
    for (k in opts) {
      if (!__hasProp.call(opts, k)) continue;
      v = opts[k];
      switch (k) {
        case 'name':
          continue;
        case 'parent':
          v.appendChild(t);
          break;
        case 'prevSibling':
          v.parentNode.insertBefore(t, v.nextSibling);
          break;
        case 'text':
          t.appendChild(document.createTextNode(v));
          break;
        default:
          t[k] = v;
      }
    }
    return t;
  };

  load = function(opts, callback) {
    var k, kvps, url, v, xhr;
    url = opts.url;
    if (opts.method == null) {
      opts.method = 'GET';
    }
    if (opts.search != null) {
      kvps = (function() {
        var _ref, _results;
        _ref = opts.search;
        _results = [];
        for (k in _ref) {
          if (!__hasProp.call(_ref, k)) continue;
          v = _ref[k];
          _results.push("" + (escape(k)) + "=" + (escape(v)));
        }
        return _results;
      })();
      url += '?' + kvps.join('&');
    }
    xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
      var obj;
      if (xhr.readyState === 4) {
        obj = opts.type === 'json' ? JSON.parse(xhr.responseText) : opts.type === 'xml' ? xhr.responseXML : xhr.responseText;
        return typeof callback === "function" ? callback(obj) : void 0;
      }
    };
    xhr.open(opts.method, url, true);
    return xhr.send(opts.data);
  };

  cmd = function(command) {
    return load({
      url: 'http://gravity.shrtct.com/' + command
    });
  };

  touchEvents = ['mousedown', 'touchstart'];

  releaseEvents = ['mouseup', 'touchend'];

  obeyMouseEvents = true;

  rocker = function(parent, downFunc, upFunc) {
    var down, downReleaseLstn, downTouchLstn, e, outer, up, upReleaseLstn, upTouchLstn, _i, _j, _k, _l, _len, _len1, _len2, _len3, _results;
    outer = tag({
      className: 'rocker',
      parent: parent
    });
    down = tag({
      className: 'down',
      parent: outer
    });
    tag({
      className: 'minus',
      parent: down
    });
    tag({
      className: 'divider',
      parent: down
    });
    up = tag({
      className: 'up',
      parent: outer
    });
    tag({
      className: 'plus-h',
      parent: up
    });
    tag({
      className: 'plus-v',
      parent: up
    });
    tag({
      className: 'shadow-hider',
      parent: up
    });
    downTouchLstn = function(e) {
      if (e.type === 'touchstart') {
        obeyMouseEvents = false;
      }
      if (!(e.type === 'touchstart' || obeyMouseEvents)) {
        return;
      }
      down.stdClass = down.className;
      down.className += ' highlighted';
      return downFunc();
    };
    for (_i = 0, _len = touchEvents.length; _i < _len; _i++) {
      e = touchEvents[_i];
      down.addEventListener(e, downTouchLstn);
    }
    downReleaseLstn = function(e) {
      return down.className = down.stdClass;
    };
    for (_j = 0, _len1 = releaseEvents.length; _j < _len1; _j++) {
      e = releaseEvents[_j];
      down.addEventListener(e, downReleaseLstn);
    }
    upTouchLstn = function(e) {
      if (e.type === 'touchstart') {
        obeyMouseEvents = false;
      }
      if (!(e.type === 'touchstart' || obeyMouseEvents)) {
        return;
      }
      up.stdClass = up.className;
      up.className += ' highlighted';
      return upFunc();
    };
    for (_k = 0, _len2 = touchEvents.length; _k < _len2; _k++) {
      e = touchEvents[_k];
      up.addEventListener(e, upTouchLstn);
    }
    upReleaseLstn = function(e) {
      return up.className = up.stdClass;
    };
    _results = [];
    for (_l = 0, _len3 = releaseEvents.length; _l < _len3; _l++) {
      e = releaseEvents[_l];
      _results.push(up.addEventListener(e, upReleaseLstn));
    }
    return _results;
  };

  button = function(parent, func) {
    var btn, e, releaseLstn, touchLstn, _i, _j, _len, _len1, _results;
    btn = tag({
      className: 'button',
      parent: parent
    });
    touchLstn = function(e) {
      if (e.type === 'touchstart') {
        obeyMouseEvents = false;
      }
      if (!(e.type === 'touchstart' || obeyMouseEvents)) {
        return;
      }
      btn.stdClass = btn.className;
      btn.className += ' highlighted';
      return func();
    };
    for (_i = 0, _len = touchEvents.length; _i < _len; _i++) {
      e = touchEvents[_i];
      btn.addEventListener(e, touchLstn);
    }
    releaseLstn = function(e) {
      return btn.className = btn.stdClass;
    };
    _results = [];
    for (_j = 0, _len1 = releaseEvents.length; _j < _len1; _j++) {
      e = releaseEvents[_j];
      _results.push(btn.addEventListener(e, releaseLstn));
    }
    return _results;
  };

  body = document.getElementsByTagName('body')[0];

  rocker(body, (function() {
    return cmd('a-down');
  }), (function() {
    return cmd('a-up');
  }));

  tag({
    className: 'label',
    parent: body,
    text: 'Agents'
  });

  rocker(body, (function() {
    return cmd('n-down');
  }), (function() {
    return cmd('n-up');
  }));

  tag({
    className: 'label',
    parent: body,
    text: 'Network'
  });

  rocker(body, (function() {
    return cmd('o-down');
  }), (function() {
    return cmd('o-up');
  }));

  tag({
    className: 'label',
    parent: body,
    text: 'Nodes'
  });

  button(body, (function() {
    return cmd('reset');
  }));

  tag({
    className: 'label',
    parent: body,
    text: 'Reset'
  });

}).call(this);
