// Generated by CoffeeScript 1.3.1
(function() {
  var body, button, cmd, load, rocker, tag,
    __hasProp = {}.hasOwnProperty;

  tag = function(opts) {
    var k, t, v, _ref;
    t = document.createElement((_ref = opts.name) != null ? _ref : 'div');
    for (k in opts) {
      if (!__hasProp.call(opts, k)) continue;
      v = opts[k];
      switch (k) {
        case 'name':
          continue;
        case 'parent':
          v.appendChild(t);
          break;
        case 'prevSibling':
          v.parentNode.insertBefore(t, v.nextSibling);
          break;
        case 'text':
          t.appendChild(document.createTextNode(v));
          break;
        default:
          t[k] = v;
      }
    }
    return t;
  };

  load = function(opts, callback) {
    var k, kvps, url, v, xhr;
    url = opts.url;
    if (opts.method == null) {
      opts.method = 'GET';
    }
    if (opts.search != null) {
      kvps = (function() {
        var _ref, _results;
        _ref = opts.search;
        _results = [];
        for (k in _ref) {
          if (!__hasProp.call(_ref, k)) continue;
          v = _ref[k];
          _results.push("" + (escape(k)) + "=" + (escape(v)));
        }
        return _results;
      })();
      url += '?' + kvps.join('&');
    }
    xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
      var obj;
      if (xhr.readyState === 4) {
        obj = opts.type === 'json' ? JSON.parse(xhr.responseText) : opts.type === 'xml' ? xhr.responseXML : xhr.responseText;
        return typeof callback === "function" ? callback(obj) : void 0;
      }
    };
    xhr.open(opts.method, url, true);
    return xhr.send(opts.data);
  };

  cmd = function(command) {
    return load({
      url: 'http://gravity.shrtct.com/' + command
    });
  };

  rocker = function(parent, downFunc, upFunc) {
    var down, outer, up;
    outer = tag({
      className: 'rocker',
      parent: parent
    });
    down = tag({
      className: 'down',
      parent: outer
    });
    tag({
      className: 'minus',
      parent: down
    });
    tag({
      className: 'divider',
      parent: down
    });
    up = tag({
      className: 'up',
      parent: outer
    });
    tag({
      className: 'plus-h',
      parent: up
    });
    tag({
      className: 'plus-v',
      parent: up
    });
    tag({
      className: 'shadow-hider',
      parent: up
    });
    down.addEventListener('mousedown', function() {
      down.stdClass = down.className;
      down.className += ' highlighted';
      return downFunc();
    });
    down.addEventListener('mouseup', function() {
      return down.className = down.stdClass;
    });
    up.addEventListener('mousedown', function() {
      up.stdClass = up.className;
      up.className += ' highlighted';
      return upFunc();
    });
    return up.addEventListener('mouseup', function() {
      return up.className = up.stdClass;
    });
  };

  button = function(parent, func) {
    var btn;
    btn = tag({
      className: 'button',
      parent: parent
    });
    btn.addEventListener('mousedown', function() {
      btn.stdClass = btn.className;
      btn.className += ' highlighted';
      return func();
    });
    return btn.addEventListener('mouseup', function() {
      return btn.className = btn.stdClass;
    });
  };

  body = document.getElementsByTagName('body')[0];

  rocker(body, (function() {
    return cmd('a-down');
  }), (function() {
    return cmd('a-up');
  }));

  tag({
    className: 'label',
    parent: body,
    text: 'Agents'
  });

  rocker(body, (function() {
    return cmd('n-down');
  }), (function() {
    return cmd('n-up');
  }));

  tag({
    className: 'label',
    parent: body,
    text: 'Network'
  });

  rocker(body, (function() {
    return cmd('o-down');
  }), (function() {
    return cmd('o-up');
  }));

  tag({
    className: 'label',
    parent: body,
    text: 'Nodes'
  });

  button(body, (function() {
    return cmd('reset');
  }));

  tag({
    className: 'label',
    parent: body,
    text: 'Reset'
  });

}).call(this);
